import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/shared/Header";
import Footer from "@/components/shared/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "AbdulMateen",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
      <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png"></link>
      </head>
    
       
  <body className="relative text-white h-full w-full ">
  
  <div
    className="absolute inset-0 z-0 bg-black/50 backdrop-blur-sm"
    style={{
      background:
        "radial-gradient(ellipse 80% 60% at 50% 0%, rgba(249, 115, 22, 0.25), transparent 70%), #000000",
    }}
  />

  {/* Main content */}
  <div className="relative z-10 min-h-screen flex flex-col">
    
    {children}
    
  </div>
</body>



    </html>
  );
}
