import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/shared/Header";
import Footer from "@/components/shared/Footer";
import Cat from "@/components/common/Cat";
import { ScrollProgress } from "@/components/ui/scroll-progress"
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "AbdulMateen",
  description: "Generated by create next app",
};

// Add this to your globals.css:
// .bg-dark { background-color: #0a0a0a; }
// .bg-brown { background-color: #2d1810; } /* or your preferred brown */

import { ReactLenis } from 'lenis/react'
import { TooltipProvider } from "@/components/ui/tooltip";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
      </head>

      <body className="relative  text-white overflow-hidden">
  {/* Global radial background */}
  <ReactLenis root>
  <div
    className="absolute inset-0 z-0"
    style={{
      background: `
        radial-gradient(
          ellipse 90% 70% at 50% 0%,
          rgba(249, 115, 22, 0.25),
          transparent 60%
        ),
        radial-gradient(
          125% 125% at 50% 10%,
          #000000 40%,
          #2b0707 100%
        )
      `,
    }}
  />
    {/* App content */}
    <TooltipProvider>
    <ScrollProgress variant={"sunset"} showPercentage className="fixed bottom-0 left-0 w-full z-50" />
      <div className="relative z-10 min-h-screen flex flex-col">
        <Cat />
        {children}
      </div>
    </TooltipProvider>
  </ReactLenis>
</body>

    </html>
  );
}
